models:
- columns:
  - name: event_type
    tests:
    - not_null
  - name: event_id
    tests:
    - not_null
  - name: user_id
    tests:
    - not_null
  - name: request_id
    tests:
    - not_null
  - name: product_id
    tests:
    - not_null
  - name: ts
    tests:
    - not_null
  name: int_product_impressions
version: 1
