name: product_click
version: 2
description: User clicks on a product

schema:
  user_id:
    type: string
    required: true
  visit_id:
    type: string
    required: true
  product_id:
    type: string
    required: true
  request_id:
    type: string
    required: true
  ts:
    type: timestamp
    required: true

default_destination: analytics_db